
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PPCRental_Project.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class ABOUT_US
{

    public int ID { get; set; }

    [Required]
    [DataType(DataType.MultilineText)]
    [StringLength(10000,MinimumLength=100)]
    public string Contents { get; set; }

    [Required]
    public string Adress { get; set; }

    public System.DateTime Update_day { get; set; }

    public int Sale_ID { get; set; }



    public virtual USER USER { get; set; }

}

}
