
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PPCRental_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class USER
{

    public USER()
    {

        this.PROPERTY = new HashSet<PROPERTY>();

        this.PROPERTY1 = new HashSet<PROPERTY>();

        this.ABOUT_US = new HashSet<ABOUT_US>();

    }


    public int ID { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Role { get; set; }

    public Nullable<bool> Status { get; set; }



    public virtual ICollection<PROPERTY> PROPERTY { get; set; }

    public virtual ICollection<PROPERTY> PROPERTY1 { get; set; }

    public virtual ICollection<ABOUT_US> ABOUT_US { get; set; }

}

}
