// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental_Project.AcceptanceTests.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PostPropertyFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "Postproject.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PostProperty", "\tAs a owner of property\r\n\tI want to post my property\r\n\tso that i can to sell prop" +
                    "erty.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "PostProperty")))
            {
                global::PPCRental_Project.AcceptanceTests.Feature.PostPropertyFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "email",
                        "password",
                        "fullname",
                        "phone",
                        "address",
                        "role"});
            table1.AddRow(new string[] {
                        "user@ppc.com",
                        "user",
                        "marketing2",
                        "0123456789",
                        "trần hưng đạo",
                        "1"});
#line 8
 testRunner.Given("the following account", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Property Type",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "BedRoom",
                        "BathRoom",
                        "ParkingPlace",
                        "Owner",
                        "Created_at",
                        "Created_post",
                        "Status",
                        "Note",
                        "Updated_at"});
            table2.AddRow(new string[] {
                        "PIS Top Apartment1",
                        "PIS_6656-Edit-stamp.jpg",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "user@ppc.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
            table2.AddRow(new string[] {
                        "PIS Top Apartment2",
                        "PIS_6656-Edit-stamp.jpg",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "user@ppc.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
            table2.AddRow(new string[] {
                        "PIS Top Apartment3",
                        "PIS_6656-Edit-stamp.jpg",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "user@ppc.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
#line 11
 testRunner.Given("the following properties", ((string)(null)), table2, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Post project successfully")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PostProperty")]
        public virtual void PostProjectSuccessfully()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post project successfully", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 19
 testRunner.When("I am at Home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("I have navigate to Login page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And("I entered \'user@ppc.com\' and \'user\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.When("I have navigate to Post page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Property Type",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "BedRoom",
                        "BathRoom",
                        "ParkingPlace",
                        "Owner",
                        "Created_at",
                        "Created_post",
                        "Status",
                        "Note",
                        "Updated_at"});
            table3.AddRow(new string[] {
                        "PIS Top Apartment5",
                        "PIS_6656-Edit-stamp.jpg",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "user@ppc.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
#line 23
 testRunner.And("I entered the following information", ((string)(null)), table3, "And ");
#line 26
 testRunner.And("I have navigate to View List of Agency Project", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Owner",
                        "Price",
                        "Content"});
            table4.AddRow(new string[] {
                        "PIS Top Apartment1",
                        "PIS_6656-Edit-stamp.jpg",
                        "user@ppc.com",
                        "10000",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops"});
            table4.AddRow(new string[] {
                        "PIS Top Apartment2",
                        "PIS_6656-Edit-stamp.jpg",
                        "user@ppc.com",
                        "10000",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops"});
            table4.AddRow(new string[] {
                        "PIS Top Apartment3",
                        "PIS_6656-Edit-stamp.jpg",
                        "user@ppc.com",
                        "10000",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops"});
            table4.AddRow(new string[] {
                        "PIS Top Apartment5",
                        "PIS_6656-Edit-stamp.jpg",
                        "user@ppc.com",
                        "10000",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops"});
#line 27
 testRunner.Then("The list of properties shoul have my new property", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
