// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PPCRental_Project.AcceptanceTests.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PropertyDetailFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "PropertyDetail.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PropertyDetail", "\tAs I want to see detail of a property\r\n\tSo we can decide to bye this property", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "PropertyDetail")))
            {
                global::PPCRental_Project.AcceptanceTests.Feature.PropertyDetailFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "email",
                        "password",
                        "fullname",
                        "phone",
                        "address",
                        "role"});
            table1.AddRow(new string[] {
                        "sale10@ppc.com",
                        "admin1",
                        "marketing2",
                        "0123456789",
                        "trần hưng đạo",
                        "1"});
#line 6
 testRunner.Given("the following account", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Property Type",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "BedRoom",
                        "BathRoom",
                        "ParkingPlace",
                        "Owner",
                        "Created_at",
                        "Created_post",
                        "Status",
                        "Note",
                        "Updated_at"});
            table2.AddRow(new string[] {
                        "PIS Top Apartment1",
                        "PIS_6656-Edit-stamp.jpg",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "sale10@ppc.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
            table2.AddRow(new string[] {
                        "PIS Top Apartment2",
                        "PIS_6656-Edit-stamp.jpg",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "sale10@ppc.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
            table2.AddRow(new string[] {
                        "PIS Top Apartment3",
                        "PIS_6656-Edit-stamp.jpg",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "sale10@ppc.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
#line 9
 testRunner.Given("the following properties", ((string)(null)), table2, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("See list the propertyname , the avatar , owner , content , price of property")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PropertyDetail")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void SeeListThePropertynameTheAvatarOwnerContentPriceOfProperty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("See list the propertyname , the avatar , owner , content , price of property", new string[] {
                        "mytag"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 16
 testRunner.Given("I open details of \'PIS Top Apartment1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "PropertyName",
                        "Avatar",
                        "Images",
                        "Property Type",
                        "Content",
                        "Street",
                        "Ward",
                        "District",
                        "Price",
                        "UnitPrice",
                        "Area",
                        "BedRoom",
                        "BathRoom",
                        "ParkingPlace",
                        "Owner",
                        "Created_at",
                        "Created_post",
                        "Status",
                        "Note",
                        "Updated_at"});
            table3.AddRow(new string[] {
                        "PIS Top Apartment1",
                        "PIS_6656-Edit-stamp.jpg",
                        "test.jpg,",
                        "Apartment",
                        "The surrounding neighborhood is very much localized with a great number of local " +
                            "shops",
                        "Điền Viên Thôn",
                        "TT Tây Đằng",
                        "Ba Vì",
                        "10000",
                        "USD",
                        "120m2",
                        "3",
                        "3",
                        "1",
                        "sale10@ppc.com",
                        "2017-11-09",
                        "2017-11-09",
                        "Đã duyệt",
                        "Done",
                        "2017-11-09"});
#line 17
 testRunner.Then("The property details have be show", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
